feature/regex for text processing
hale-Dennis/group2-text-processing-tool pull request #15
Opened 2024-07-25 21:07 UTC by sayv-xo

implemented feature to handle regex operations

2024-07-25 21:24 UTC, hale-Dennis approved these changes
Great

2024-07-25 23:38 UTC, arkohaddoebenezer requested changes

2024-07-25 23:38 UTC, arkohaddoebenezer commented on src/main/java/org/group2/textprocessingtool/controllers/TextProcessingMainController.java
>  import javafx.stage.FileChooser;
Please are you sure this ought to be removed?? are they not being used on other branches?

2024-07-25 23:44 UTC, arkohaddoebenezer commented on src/main/java/org/group2/textprocessingtool/controllers/TextProcessingMainController.java
>  import javafx.stage.FileChooser;
> Please are you sure this ought to be removed?? are they not being used on other branches?

![Screenshot (337)](https://github.com/user-attachments/assets/aa7a60b1-b095-471e-8c1d-c26ba11d310b)

2024-07-26 08:02 UTC, arkohaddoebenezer approved these changes
we import them incase it breaks the code

2024-07-26 08:06 UTC, merged